version: '3'
services:
    build:
        image: kspeer825/python:latest
        pull_policy: missing
        volumes:
            - ./:/usr/local/src
            - $HOME/.zshrc:/root/.zshrc
        working_dir: /usr/local/src
        network_mode: host
        command: bash -c 'bash'
