pipeline {

    agent any

    environment {
        SLEEP_TIME = 2
        SECRET_TEXT = credentials('TEST_SECRET_TEXT')
    }

    stages {

        stage('Build') {
            steps {
                sh 'echo "Building..."'
                sh '''
                    echo "Can execute multiple commands within a single step"
                    ls -alh
                '''
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Testing..."'
                retry(3) {
                    sh 'echo "I remembered to put echo before my string."'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying..."'
                timeout(time: 3, unit: 'SECONDS') {
                    sh 'sleep $SLEEP_TIME'
                }
                sh 'echo "($SECRET_TEXT)"'
            }
        }
    }
    post {
        always {echo 'I always execute.'}
        success {echo 'I execute on successful builds.'}
        failure {echo 'I execute on failed builds.'}
        unstable {echo 'I execute when build is unstable.'}
    }
}