name: 'Build Deploy Speer Porftolio Website'

on:
  push:
    branches: [ 'main' ]
    path:
      - 'projects/website/speerportfolio/**'
      - '!projects/website/speerportfolio/README.md'

  workflow_dispatch:
    branches: [ 'main' ]
    inputs:
      awsRegion:
        type: choice
        default: 'us-east-2'
        options:
          - 'us-east-2'
          - 'us-east-1'
      awsS3BucketName:
        type: string
        default: 'kyle.speer.portfolio'

jobs:
  build_deploy:
    name: 'Build/Deploy App'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: ${{ inputs.awsRegion || 'us-east-2' }}
      AWS_BUCKET: ${{ inputs.awsS3BucketName || 'kyle.speer.portfolio' }}

    defaults:
      run:
        shell: bash
        working-directory: projects/website

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build & Upload
        run: ./build_upload.sh ${{ env.AWS_BUCKET }}

      - name: Deploy
        run: ./refresh_cdn.sh ${{ env.AWS_BUCKET }}
