name: 'Build Deploy Speer Porftolio Website'

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'projects/website/speerportfolio/**'
      - '!projects/website/speerportfolio/README.md'

  workflow_dispatch:
    branches: [ 'main' ]
    inputs:
      awsRegion:
        type: choice
        default: 'us-east-2'
        options:
          - 'us-east-2'
          - 'us-east-1'

jobs:
  build_deploy:
    name: 'Build/Deploy App'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: ${{ inputs.awsRegion || 'us-east-1' }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

    defaults:
      run:
        shell: bash
        working-directory: projects/website/infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, Upload, & Deploy
        run: make app-deploy
