name: 'Spin Up Infra'

on:
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      plan:
        type: boolean
        description: Output the Terraform plan.
      apply:
        type: boolean
        description: Apply the Terraform plan.


jobs:
  deploy:
    name: 'Deploy Infra'
    runs-on: ubuntu-latest
    environment: production
    env:
      ACCESS_KEY_ID: ${{ secrets.PROD_USER_AWS_ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.PROD_USER_AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ inputs.plan }}
        run: terraform plan -var="aws_region=us-east-2" -var="aws_access_key=${{ env.ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.SECRET_ACCESS_KEY }}"

      - name: Terraform Apply
        if: ${{ inputs.apply }}
        run: terraform apply -auto-approve -var="aws_region=us-east-2" -var="aws_access_key=${{ env.ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.SECRET_ACCESS_KEY }}"
