name: 'Spin Up Infra'

on:
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      plan:
        type: boolean
        description: Output the Terraform plan.
      apply:
        type: boolean
        description: Apply the Terraform plan.


jobs:
  deploy:
    name: 'Deploy Infra'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

    defaults:
      run:
        shell: bash
        working-directory: projects/website/infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Terraform Init
        run: make init

      - name: Terraform Format and Validate
        run: make test

      - name: Terraform Plan
        if: ${{ inputs.plan }}
        run: make init plan

      - name: Terraform Apply
        if: ${{ inputs.apply }}
        run: make init plan apply
