name: 'Release IDE'

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'projects/my_ide/**'
      - '!projects/my_ide/README.md'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
